log:
  level: debug
  disable_sentry: true

db:
  url: postgres://max:pass@localhost:5435/jwt_server?sslmode=disable

amqp:
  topic: "auth-svc"
  publisher: "amqp://guest:guest@localhost:5672/" #module_publisher
  subscriber: "amqp://guest:guest@localhost:5672/" #module_receiver
  orchestrator: "orchestrator"

listener:
  addr: :7000

jwt:
  secret: SuPeR SeCrEt PhRaSe
  refresh_life: 6h
  access_life: 2m

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: Auth
  service_port: 80
