log:
  level: debug
  disable_sentry: true

db:
  url: postgres://max:pass@localhost:5432/jwt_server?sslmode=disable

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: jwt-service
  service_port: 80
