version: '3.3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "jwt_server"
      POSTGRES_USER: "max"
      POSTGRES_PASSWORD: "pass"
    ports:
      - '5432:5432'

